
build:
	$(info ************** Building C++ Programs **************)
	cd Array && $(MAKE)
	cd Structures && $(MAKE)
	cd Pointer-To-Structure && $(MAKE)
	cd Functions && $(MAKE)
	cd Parameter-Passing-Methods && $(MAKE)
	cd Array-As-Parameter && $(MAKE)
	cd Structure-As-Parameter && $(MAKE)
	cd Structures-and-Functions && $(MAKE)
	cd Converting-C-to-CPP-Class && $(MAKE)
	cd Template-Classes && $(MAKE)

run:
	$(info ************** Running C++ Programs **************)
	cd Array && ./main
	cd Structures && ./main
	cd Pointer-To-Structure && ./main
	cd Functions && ./main
	cd Parameter-Passing-Methods && ./main
	cd Array-As-Parameter && ./main
	cd Structure-As-Parameter && ./main
	cd Structures-and-Functions && ./main
	cd Converting-C-to-CPP-Class && ./main
	cd Template-Classes && ./main

clean:
	$(info ************** Cleaning C++ Programs **************)
	cd Array && rm main
	cd Structures && rm main
	cd Pointer-To-Structure && rm main
	cd Functions && rm main
	cd Parameter-Passing-Methods && rm main
	cd Array-As-Parameter && rm main
	cd Structure-As-Parameter && rm main
	cd Structures-and-Functions && rm main
	cd Converting-C-to-CPP-Class && rm main
	cd Template-Classes && rm main

test:
	$(info ************** Testing C++ Programs **************)